[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "myrepo"
version = "0.0.1"

[tool.setuptools]
package-dir = { "utils" = "utils", "utils_training" = "utils_training", "models" = "models" }
packages = ["utils", "utils_training", "models"]
